services:
  mention-bot:
    build: .
    container_name: mention-bot
    restart: always # unless-stopped
    env_file:
      - .env
    volumes:
      - ./database.sqlite3:/app/database.sqlite3
      - ./logs.log:/app/logs.log
